version: '3'

services:
  fullstack-party-api:
    build: ./php
    working_dir: /var/www/
    container_name: fullstack-party-api
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/:delegated
      - ./logs/apache:/var/log/apache2:delegated
