version: '2'

services:
  fullstack-party-ui:
    build:
      context: ./node
      dockerfile: Dockerfile.dev
    environment:
      ROOTURL: ${ROOTURL}
      APIURL: ${APIURL}
      GITHUB_URL: ${GITHUB_URL}
      GITHUB_API_URL: ${GITHUB_API_URL}
      CLIENT_ID: ${CLIENT_ID}
    working_dir: /var/www/
    container_name: fullstack-party-ui
    ports:
      - '2201:2201'
    volumes:
      - ../:/var/www/
